### ISSUE TITLE
Connection from left_leg inertialMTB port not working when running Yarp with Gazebo clock

### ISSUE THREAD

**Issue by nunoguedelha** [robotology-playground/sensors-calib-inertial#1]
This issue was initially created on March 3, and moved from its original repository https://github.com/nunoguedelha/jointOffsetCalibInertial/issues/1.

Neither of the following commands will set a successful connection:
```
$> yarp read ... envelope /icubSim/left_leg/inertialMTB

$> yarp read /dumper/test
$> yarp connect /icubSim/left_leg/inertialMTB /dumper/test
```
Actually the connection is established but no data seems to be exchanged:
```
yarp: Port /tmp/port/1 active at tcp://10.255.36.3:10055/
yarp: Receiving input from /icubSim/left_leg/inertialMTB to /tmp/port/1 using tcp
```

**Comment by nunoguedelha** [comment]
This is caused by an issue on Gazebo. A workaround has been implemented. More details to come.

**Comment by barbalberto** [comment]
There are some known issues with yarp when using network clock and I'm working to solve them. 
Can you try the yarp `clockWIP` yarp branch to see if it works better?

**Comment by nunoguedelha** [comment]
@barbalberto Thanks for the info, I will test it tomorrow. Meanwhile, I had fixed the issue with a workaround by changing 1 single line in the `libYARP_OS` module. I'm opening an issue with the details and a short first analysis, just in case the issue is different.
For the record, I'm using an unreleased gazebo yarp plugin for emulating accelerometers, so you might never have run into my use case. Anyway, as far a s I could understand, it is a real issue not related to the plugin.

**Comment by nunoguedelha** [comment]
@barbalberto my motivation for keeping my workaround is that your branch has significant changes and is actually around 30 commits behind the `devel` branch commit I'm based on (yarp: 1cc5b46a72c1923255108381849ba52c03f60d3d - 28 feb).

**Comment by nunoguedelha** [comment]
This issue hasn't occurred again for long with current Yarp version. Closing the issue.
